services:
  backend:
    image: node:18-alpine
    command: sh -c "npm install && cp ./instalation/oauth/authorize-handler.js ./node_modules/oauth2-server/lib/handlers/authorize-handler.js && npm run start"
    ports:
      - 3000:3000
    working_dir: /Backend
    volumes:
      - ./:/Backend
    environment:
      PORT: 3000
      POSTGRES_HOST: db 
      POSTGRES_USER: tfggtdUser
      POSTGRES_PASSWORD: nodenodito@69
      POSTGRES_DB: tfggtd

  db:
    image: postgres
    volumes:
      - posgresql-data:/var/lib/postgresql/data
      - ../BBDD/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: tfggtdUser
      POSTGRES_PASSWORD: nodenodito@69
      POSTGRES_DB: tfggtd
    ports:
      - 127.0.0.1:5432:5432

volumes:
  posgresql-data: