services:
  backend:
    image: node:18-alpine
    command: sh -c "npm install && npm run start"
    ports:
      - 443:443
    working_dir: /Backend
    volumes:
      - ./:/Backend
      - /etc/ssl/certs/:/etc/ssl/certs/
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/intermediate.pem
      NODE_ENV: production
      PORT: 443
      HOSTNAME: 16.16.226.94.nip.io
      POSTGRES_HOST: db
      POSTGRES_USER: tfggtdUser
      POSTGRES_PASSWORD: nodenodito@69
      POSTGRES_DB: tfggtd

  db:
    image: postgres
    volumes:
      - posgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: tfggtdUser
      POSTGRES_PASSWORD: nodenodito@69
      POSTGRES_DB: tfggtd
    ports:
      - 5432:5432

volumes:
  posgresql-data: